/* UI 互動：篩選、表單、複製提示。核心指令不在這裡定義。 */
(function(){"use strict";const M=window.SBSTermux,$=id=>document.getElementById(id);let category="全部",editing=null;const toast=window.SlowlyToast?.create?.($("toast"),{duration:2300});function notify(message){if(toast)toast.show(message);else{$("toast").textContent=message;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2300);}}
async function copy(text){if(window.SlowlyClipboardCopy?.copy)return window.SlowlyClipboardCopy.copy(text);if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);throw new Error("複製元件未載入，請檢查網路連線。");}
function projectUI(){const p=M.current();$("project-select").replaceChildren();M.projects().forEach(v=>{const opt=document.createElement("option");opt.value=v.id;opt.textContent=v.name;$("project-select").append(opt);});$("project-select").value=p.id;$("project-path").textContent=p.path;render();}
function render(){const q=$("search").value.trim().toLowerCase(),p=M.current(),items=M.entries.filter(v=>(category==="全部"||v.cat===category)&&(!q||[v.title,v.desc,v.cat,v.id].join(" ").toLowerCase().includes(q)));$("result-count").textContent=`${items.length} 組`;$("empty").hidden=items.length>0;const list=$("command-list");list.replaceChildren();items.forEach(item=>{const card=document.createElement("article");card.className="command";const top=document.createElement("div");top.className="command-top";const info=document.createElement("div"),tag=document.createElement("span"),h=document.createElement("h3"),desc=document.createElement("p");tag.className="tag";tag.textContent=item.cat;h.textContent=item.title;desc.textContent=item.desc;info.append(tag,h,desc);const button=document.createElement("button");button.type="button";button.className="copy-command";button.textContent="複製整段";const command=item.body(p);button.addEventListener("click",async()=>{try{await copy(command);notify("已複製整段指令");}catch(err){notify(err.message);}});top.append(info,button);const wrap=document.createElement("div"),pre=document.createElement("pre"),code=document.createElement("code");wrap.className="code-wrap";code.textContent=command;pre.append(code);wrap.append(pre);card.append(top,wrap);if(item.risk){const warn=document.createElement("p");warn.className="warning";warn.textContent="注意｜"+item.risk;card.append(warn);}list.append(card);});}
const nav=$("category-nav");["全部",...new Set(M.entries.map(v=>v.cat))].forEach(cat=>{const b=document.createElement("button");b.type="button";b.className="category";b.textContent=cat;b.setAttribute("aria-pressed",String(cat===category));b.addEventListener("click",()=>{category=cat;nav.querySelectorAll("button").forEach(el=>el.setAttribute("aria-pressed",String(el===b)));render();});nav.append(b);});
$("search").addEventListener("input",render);$("reset-search").onclick=()=>{$("search").value="";render();};$("project-select").addEventListener("change",e=>{M.select(e.target.value);projectUI();});$("copy-path").onclick=async()=>{try{await copy(M.current().path);notify("已複製專案路徑");}catch(err){notify(err.message);}};
function openForm(id){editing=id;const p=id?M.projects().find(v=>v.id===id):null;$("dialog-title").textContent=id?"編輯專案":"新增專案";$("project-name").value=p?.name||"";$("project-directory").value=p?.path||"";$("project-dialog").showModal();$("project-name").focus();}function closeForm(){$("project-dialog").close();}$("add-project").onclick=()=>openForm(null);$("edit-project").onclick=()=>openForm(M.current().id);$("close-dialog").onclick=closeForm;$("cancel-dialog").onclick=closeForm;$("project-form").addEventListener("submit",e=>{e.preventDefault();try{M.upsert({name:$("project-name").value,path:$("project-directory").value},editing);closeForm();projectUI();notify("專案已儲存");}catch(err){notify(err.message);}});$("remove-project").onclick=()=>{const p=M.current();if(!window.confirm(`從指令本移除「${p.name}」？\n只刪除瀏覽器中的專案設定，不會刪除手機檔案。`))return;try{M.remove(p.id);projectUI();notify("已移除專案設定");}catch(err){notify(err.message);}};projectUI();
})();
